# Generated by Django 4.2.30 on 2026-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_id_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female')], default=''),
        ),
    ]
