# Generated by Django 4.2.30 on 2026-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_id',
            field=models.TextField(unique=True),
        ),
    ]
