# Generated by Django 4.2.30 on 2026-06-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.TextField()),
                ('file_size', models.IntegerField()),
                ('file_type', models.TextField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG')])),
                ('upload_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_resources', to='api.user')),
            ],
            options={
                'db_table': 'file_resources',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
