# Generated by Django 4.2.30 on 2026-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fileresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='is_public',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='permission_level',
            field=models.TextField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('private', 'Private')], default='private'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='thumbnail_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
