# Generated by Django 4.2.30 on 2026-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fileresource_is_public_and_more'),
    ]

    operations = [
        # Add database indexes for frequently queried fields
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['file_type'], name='api_fileresource_file_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['permission_level'], name='api_fileresource_permission_level_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['uploaded_at'], name='api_fileresource_uploaded_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='api_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='api_user_created_at_idx'),
        ),
    ]
