# Generated by Django 4.2.30 on 2026-06-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
    ]
