# Generated by Django 4.2.30 on 2026-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_fileresource_api_fileresource_file_type_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fileresource',
            name='api_fileresource_file_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileresource',
            name='api_fileresource_permission_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileresource',
            name='api_fileresource_uploaded_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='api_user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='api_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='api_user_created_at_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='diaspora',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profession_bodies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
