# Generated by Django 4.2.30 on 2026-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_fileresource_api_fileresource_file_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='diaspora',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profession_bodies',
            field=models.JSONField(default=list, blank=True),
        ),
    ]