# Generated by Django 4.2.30 on 2026-06-24 06:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_diaspora_and_profession_bodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='county',
            field=models.CharField(blank=True, help_text='Required if country is Kenya', max_length=50),
        ),
    ]
