# Generated by Django 4.2.30 on 2026-06-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_member_country_member_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='diaspora',
        ),
    ]
