# Generated by Django 4.2.30 on 2026-06-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_member_diaspora'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file_type', models.TextField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_adverts', to='api.user')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_adverts', to='api.fileresource')),
            ],
            options={
                'db_table': 'job_adverts',
                'ordering': ['-created_at'],
            },
        ),
    ]
