# Generated by Django 4.2.30 on 2026-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_jobadvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
