# Generated by Django 4.2.30 on 2026-06-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobadvert_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_adverts', to='api.fileresource'),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='file_type',
            field=models.TextField(blank=True, choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG')], default=''),
        ),
    ]
